# Generated by Django 4.0.4 on 2022-06-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bots',
            field=models.ManyToManyField(blank=True, to='api.bot'),
        ),
    ]
