# Generated by Django 4.0.4 on 2022-06-04 11:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_token_rename_token_bot_bot_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AlterField(
            model_name='bot',
            name='bot_token',
            field=models.CharField(default=api.models.random_string, max_length=30),
        ),
    ]
