# Generated by Django 4.0.4 on 2022-06-04 11:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_token_alter_bot_bot_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=api.models.random_string, max_length=30)),
                ('is_supertoken', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='supertoken status')),
                ('bots', models.ManyToManyField(blank=True, help_text='Bots edit field.', to='api.bot')),
            ],
        ),
    ]
