# Generated by Django 4.0.4 on 2022-06-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='token',
            new_name='name',
        ),
    ]
