# Generated by Django 4.0.4 on 2022-06-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_token_token_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
