# Generated by Django 4.0.4 on 2022-06-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_token_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
