# Generated by Django 4.0.4 on 2022-06-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_token_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bots',
            field=models.ManyToManyField(blank=True, help_text='Bots edit field.', null=True, to='api.bot'),
        ),
        migrations.AlterField(
            model_name='token',
            name='is_supertoken',
            field=models.BooleanField(default=False, help_text='Designates that this token has all permissions without explicitly assigning them.', verbose_name='supertoken status'),
        ),
    ]
