# Generated by Django 4.0.4 on 2022-06-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_task_alter_customuser_bots_alter_token_is_supertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
