# Generated by Django 4.0.4 on 2022-06-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bots',
            field=models.ManyToManyField(blank=True, help_text='Bots edit field.', to='api.bot'),
        ),
    ]
