# Generated by Django 4.0.4 on 2022-06-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_customuser_bots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_sended', models.BooleanField()),
                ('is_delivered', models.BooleanField()),
                ('is_completed', models.BooleanField()),
                ('to_bot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.bot')),
                ('to_token', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.token')),
            ],
        ),
    ]
