# Generated by Django 4.0.4 on 2022-06-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_description_token_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='to_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bot'),
        ),
        migrations.AlterField(
            model_name='task',
            name='to_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.token'),
        ),
    ]
