# Generated by Django 4.0.4 on 2022-06-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_task_to_bot_alter_task_to_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_delivered',
            new_name='delivered',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_sended',
            new_name='sended',
        ),
    ]
