# Generated by Django 4.0.4 on 2022-10-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_is_completed_task_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='bot_token',
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='sended',
            field=models.BooleanField(default=False),
        ),
    ]
