# Generated by Django 4.1.2 on 2022-10-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_bot_bot_token_alter_task_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
